### ISSUE TITLE
sqlite bench

### ISSUE THREAD

**Issue by gedw99** [pocketbase/benchmarks#2]
https://github.com/delaneyj/go-sqlite-bench

hey @ganigeorgiev 

I figured this is useful...

The numbers are really interesting and maybe its worth revisiting the base sqlite driver Pocketable uses.

**Comment by ganigeorgiev** [comment]
Another user already posted it in https://github.com/pocketbase/pocketbase/discussions/3955.
I'm aware of it but for now there are no plans to switch from the standard `database/sql` to 3rd party db driver abstraction.

Performance can definitely be improved but it is not a priority at the moment and unless there is a critical/blocker performance issue these type of tasks are left for somewhere before the final v1 release.
